FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

# Use a minimal alpine image to store the built files
FROM alpine:latest

# Create directory for the app
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]
