version: "3.9"

services:
  # Frontend (nginx with certbot)
  tour-frontend:
    container_name: tour-frontend
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./frontend/nginx-certbot.env
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/.nginx/user_conf.d:/etc/nginx/user_conf.d:ro
      - nginx_secrets:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

  # Backend (PostgreSQL)
  tour-backend:
    container_name: tour-backend
    image: bitnami/postgresql:16.0.0
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - backend:/bitnami/postgresql
    ports:
      - "${DB_PORT:-5431}:5432"
    networks:
      - webnet

volumes:
  backend:
  nginx_secrets:  # Add this volume for storing certificates

networks:
  webnet:
    driver: bridge
