version: "3.9"

services:
  # Frontend (nginx with certbot)
  tour-frontend:
    container_name: tour-frontend
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./frontend/nginx-certbot.env.dev
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/.nginx/dev/user_conf.d:/etc/nginx/user_conf.d:ro
      - nginx_secrets:/etc/letsencrypt
      - uploads:/usr/share/nginx/uploads:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

  # Database (PostgreSQL)
  tour-db:
    container_name: tour-db
    image: bitnami/postgresql:16.0.0
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "${DB_PORT:-5431}:5432"
    networks:
      - webnet

volumes:
  postgres_data:
  nginx_secrets:  # Add this volume for storing certificates
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/backend/uploads
      o: bind

networks:
  webnet:
    driver: bridge
