version: "3.9"

services:
  # Frontend (nginx with certbot)
  tour-frontend:
    container_name: tour-frontend
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/.nginx/dev/user_conf.d:/etc/nginx/conf.d:ro
      - ./backend/uploads:/usr/share/nginx/uploads:ro
    ports:
      - "80:80"
    networks:
      - webnet

  # Database (PostgreSQL)
  tour-db:
    container_name: tour-db
    image: bitnami/postgresql:16.0.0
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "${DB_PORT:-5431}:5432"
    networks:
      - webnet

volumes:
  postgres_data:
  nginx_secrets:  # Add this volume for storing certificates
  uploads:

networks:
  webnet:
    driver: bridge
